# FinanceForge Application Configuration
spring:
  application:
    name: financeforge-api
  profiles:
    active: dev

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${DB_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: none  # Flyway will manage schema
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,datasource
    endpoint:
      health:
        show-details: when-authorized

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    com.financeforge: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
  logging:
    level:
      com.financeforge: INFO
      org.hibernate.SQL: WARN