-- V001__Initial_flyway_test.sql
-- Test migration to verify Flyway setup works with Oracle

CREATE TABLE flyway_test (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_message VARCHAR2(100) NOT NULL,
    created_date DATE DEFAULT SYSDATE
);

-- Insert a test record to prove it worked
INSERT INTO flyway_test (test_message)
VALUES ('Flyway setup successful - FF-003a complete!');

COMMIT;