-- Initial test migration to verify Flyway setup
-- This creates a simple test table to prove everything works

CREATE TABLE flyway_test (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_message VARCHAR2(100) NOT NULL,
    created_date DATE DEFAULT SYSDATE
);

-- Insert a test record to prove it worked
INSERT INTO flyway_test (test_message)
VALUES ('Flyway setup successful!');

COMMIT;